

source "https://rubygems.org"

gem "net-smtp", "~> 0.5.1"
gem "pony",     "~> 1.13"
gem "puma",     "~> 6.6"
gem "sinatra",  "~> 4.1"
gem "rackup",   "~> 2.2"

gem "google-protobuf", "~> 4.31.1"

gem "ddtrace", "~> 1.0"
